### ISSUE TITLE
Having issues using it on a Mac OS X

### ISSUE THREAD

**Issue by daviddias** [neurobin/php2html#3]
Hi there,

Was trying to use your tool and stumbled upon this error:

```
» php2html
zsh: /Users/imp/Downloads/php2html-release/php2html: bad interpreter: /usr/bin/python3: no such file or directory
```

Seems that the script is using `#!/usr/bin/python3` instead of `#!/usr/bin/env python3`. For Mac OS X users that are using El Capitan or later, we have to disable [Apple's System Integrity Protection](https://support.apple.com/en-us/HT204899) since we can't really cp or ln python3 into /usr/bin with it on.

I was looking for the original code to PR this change but couldn't find it. Mind updating it and releasing it again? Thanks!

**Comment by neurobin** [comment]
You can probably do this:

```python
python3 /path/to/php2html [options]
```

**Comment by neurobin** [comment]
Anyway, updated the shebang to `/usr/bin/env python3`. If this fixes the problem, then your PR will be invalid.

**Comment by daviddias** [comment]
Thank you @neurobin ! :)
